version: "3.7"

services:
  mysql:
    image: "mysql:8"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: klonieckiweb
    ports:
      - 7001:3306
    volumes:
      - mysql-vol:/var/lib/mysql

volumes:
  mysql-vol: ~
